version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - run:
        name: Run lint
        command: yarn lint
    - run:
        name: Run prettier
        command: yarn format